[package]
name = "water_buffer"
version = "0.1.0"
edition = "2024"
authors = ["HassanSharara"]
repository = "https://github.com/HassanSharara/water_buffer"
homepage = "https://github.com/HassanSharara/water_buffer"
license = "MIT"
readme = "README.md"
categories = ["memory-management","caching","network-programming"]
keywords = ["buffer","water-buffer","water_buffer"]

[dev-dependencies]
bytes = "1.11.0"
